apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: thatladydev/devfest-notifi-saas:latest
        env:
          - name: APP_ENV
            value: "production"
          - name: APP_URL
            value: "http://notification-service"
        ports:
          - containerPort: 80
          - containerPort: 443
          - containerPort: 9000