apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: thatladydev/devfest-auth0-saas:v1.0
        env:
          - name: APP_ENV
            value: "production"
          - name: APP_URL
            value: "http://auth-service"
        ports:
          - containerPort: 80
          - containerPort: 443
          - containerPort: 9000