apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: billing-service
  template:
    metadata:
      labels:
        app: billing-service
    spec:
      containers:
      - name: billing-service
        image: thatladydev/devfest-billify-saas:v1.0
        env:
          - name: APP_ENV
            value: "production"
          - name: APP_URL
            value: "http://billing-service"
        ports:
          - containerPort: 80
          - containerPort: 443
          - containerPort: 9000